services:
    nodejs:
        container_name: machines-monitor
        #restart: always
        image: node:20
        user: node
        command: bash -c "npm install && npm update && npm start"
        environment:
            NODE_ENV: production
            TZ: America/Chicago
        ports:
            - "3043:3043"
        volumes:
            - ./monitor:/home/node/monitor:rw
        working_dir: /home/node/monitor
